package wheel.client

import com.raquo.laminar.api.L.*
import wheel.api.ServiceRPC  // Generated by Airframe plugin (run sbt frontend/compile first)
import org.scalajs.dom
import wvlet.airframe.http.Http

object App {
  def main(args: Array[String]): Unit = {
    renderOnDomContentLoaded(
      dom.document.getElementById("app"),
      appElement()
    )
  }

  def appElement(): Element = {
    val nameVar = Var("World")  // Reactive variable
    val greetingSignal = nameVar.signal  // Signal for reactivity

    val rpcClient = ServiceRPC.newRPCAsyncClient(Http.client.newAsyncClient("http://localhost:8080"))  // Airframe RPC client

    div(
      h1("Hello Laminar + Airframe RPC!"),
      input(
        `type` := "text",
        placeholder := "Enter name",
        onInput.mapToValue --> nameVar
      ),
      button(
        "Greet",
        onClick --> { _ =>
          rpcClient.Greeter.greet(nameVar.now()).run { response =>
            dom.window.alert(response)  // Display RPC response
          }
        }
      ),
      p(child.text <-- greetingSignal.map(name => s"Current name: $name"))  // Reactive update
    )
  }
}
